apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-presidio-anonymizer-service
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.AppVersion}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    app.kubernetes.io/component: presidio-anonymizer
spec:
  type: {{.Values.masking.presidio.anonymizer.service.type}}
  ports:
  - port: {{.Values.masking.presidio.anonymizer.service.externalPort}}
    targetPort: {{.Values.masking.presidio.anonymizer.service.internalPort}}
    protocol: TCP
    name: {{.Values.masking.presidio.anonymizer.service.name}}
  selector:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/component: presidio-anonymizer