apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-worker-deployment
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.AppVersion}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{.Release.Name}}
      app.kubernetes.io/name: {{.Chart.Name}}
      app.kubernetes.io/component: worker
  template:
    metadata:
      name: {{.Release.Name}}-worker
      namespace: {{.Values.namespace}}
      labels:
        app.kubernetes.io/instance: {{.Release.Name}}
        app.kubernetes.io/name: {{.Chart.Name}}
        app.kubernetes.io/version: {{.Chart.AppVersion}}
        app.kubernetes.io/managed-by: {{.Release.Service}}
        app.kubernetes.io/component: worker
    spec:
      containers:
      - name: worker
        image: {{.Values.docker.registry}}/{{.Values.worker.image}}:{{.Values.worker.tag}}
        imagePullPolicy: Always
        command: ["celery"]
        args: ["-A", "app.worker", "worker", "-l", "INFO"]
        env:
        - name: DOMAIN
          value: {{.Values.cluster.host}}
        - name: ENVIRONMENT
          value: "production"
        - name: POSTGRES_PASSWORD
          value: {{.Values.postgresql.password}}
        - name: POSTGRES_SERVER
          value: "{{.Release.Name}}-postgresql-service.{{.Values.namespace}}.svc.cluster.local"
        - name: REDIS_PASSWORD
          value: {{.Values.redis.password}}
        - name: REDIS_SERVER
          value: "{{.Release.Name}}-redis-service.{{.Values.namespace}}.svc.cluster.local"
        - name: SMTP_HOST
          value: {{.Values.backend.smtp.host}}
        {{- if .Values.backend.smtp.requireAuthentication }}
        - name: SMTP_USER
          value: {{.Values.backend.smtp.user}}
        - name: SMTP_PASSWORD
          value: {{.Values.backend.smtp.password}}
        {{- end }}
        - name: EMAILS_FROM_EMAIL
          value: {{.Values.backend.emailsFromEmail}}
        - name: EMAILS_FROM_NAME
          value: {{.Values.backend.emailsFromName}}
        - name: MINIO_SERVER
          value: "{{.Release.Name}}-minio.{{.Values.namespace}}.svc.cluster.local"
      {{ if .Values.docker.requireAuthentication -}}
      imagePullSecrets:
      - name: arena-docker-registry-secret
      {{- end }}