apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-worker-deployment
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.AppVersion}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{.Release.Name}}
      app.kubernetes.io/name: {{.Chart.Name}}
      app.kubernetes.io/component: worker
  template:
    metadata:
      name: {{.Release.Name}}-worker
      namespace: {{.Values.namespace}}
      labels:
        app.kubernetes.io/instance: {{.Release.Name}}
        app.kubernetes.io/name: {{.Chart.Name}}
        app.kubernetes.io/version: {{.Chart.AppVersion}}
        app.kubernetes.io/managed-by: {{.Release.Service}}
        app.kubernetes.io/component: worker
    spec:
      containers:
      - name: worker
        image: {{.Values.docker.registry}}/{{.Values.worker.image}}
        imagePullPolicy: Always
        command: ["celery"]
        args: ["-A", "worker", "worker", "-l", "INFO", "-I", "worker.evaluation"]
        ports:
        - containerPort: {{.Values.gateway.service.internalPort}}
        env:
        - name: POSTGRES_PASSWORD
          value: {{.Values.database.password}}
        - name: POSTGRES_SERVER
          value: "{{.Release.Name}}-database-service.{{.Values.namespace}}.svc.cluster.local"
        - name: REDIS_PASSWORD
          value: {{.Values.store.password}}
        - name: REDIS_SERVER
          value: "{{.Release.Name}}-store-service.{{.Values.namespace}}.svc.cluster.local"
        - name: PRESIDIO_ANALYZER_SERVER
          value: "{{.Release.Name}}-presidio-analyser-service.{{.Values.namespace}}.svc.cluster.local"
        - name: PRESIDIO_ANALYZER_PORT
          value: {{.Values.masking.presidio.anonymizer.service.externalPort | quote}}
        - name: PRESIDIO_ANONYMIZER_SERVER
          value: "{{.Release.Name}}-presidio-anonymizer-service.{{.Values.namespace}}.svc.cluster.local"
        - name: PRESIDIO_ANONYMIZER_PORT
          value: {{.Values.masking.presidio.anonymizer.service.externalPort | quote}}
      imagePullSecrets:
      - name: {{ .Release.Name -}}-docker-registry-secret