namespace: default

docker:
  registry: ghcr.io/arena-ai
  requireAuthentication: False
  username: arena
  password: ""

# Cluster configuration
cluster:
  provider: AKS
  ingress: nginx
  host: arena.sarus.app
  tls:
    enabled: true
    issuer:
      # name: letsencrypt-staging
      name: letsencrypt-prod
      # server: https://acme-staging-v02.api.letsencrypt.org/directory
      server: https://acme-v02.api.letsencrypt.org/directory
      email: arena@sarus.app
      # privateKeySecretRef: letsencrypt-staging
      privateKeySecretRef: letsencrypt-prod
    secretName: letsencrypt-secret

# PostgreSQL configuration
postgresql:
  image: postgres
  user: postgres
  password: ""
  db: app

# Redis configuration
redis:
  image: redis
  password: ""

# Backend configuration
backend:
  image: arena_backend
  tag: main
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 80
    name: http
  firstSuperUser:
    user: ""
    password: ""
  usersOpenRegistration: false
  smtp:
    host: smtp-relay.gmail.com
    requireAuthentication: False
    user: arena@sarus.app
    password: ""
  emailsFromEmail: arena@sarus.app
  emailsFromName: "Sarus Arena"

# Worker configuration
worker:
  image: arena_backend
  tag: main
  service:
    type: ClusterIP

# Frontend configuration
frontend:
  image: arena_frontend
  tag: main
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 80
    name: http

# Ingress values (see: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml)
ingress-nginx:
  # namespaceOverride: sarus
  controller:
    replicaCount: 2
    publishService:
      enabled: true
    nodeSelector:
      kubernetes.io/os: linux
    defaultBackend:
      nodeSelector:
        kubernetes.io/os: linux
    admissionWebhooks:
      patch:
        nodeSelector:
          kubernetes.io/os: linux
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: ""

cert-manager: #defined by either the name or alias of your dependency in Chart.yaml
  namespace: default

# This is a bit legacy but let's keep it
masking:
  presidio:
    registry: mcr.microsoft.com
    # The text analyzer
    analyzer:
      image: presidio-analyzer
      tag: latest
      replicas: 1
      # imagePullPolicy: Always
      container:
        resources:
          requests:
            memory: "1500Mi"
            cpu: "1500m"
          limits:
            memory: "3000Mi"
            cpu: "2000m"
      service:
        type: ClusterIP
        externalPort: 80
        internalPort: 5001
        name: http
    # The text anonymizer
    anonymizer:
      image: presidio-anonymizer
      tag: latest
      replicas: 1
      # imagePullPolicy: Always
      container:
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      service:
        type: ClusterIP
        externalPort: 80
        internalPort: 5001
        name: http
