"""pydantic model to document_data_extractor

Revision ID: 0cf11907d837
Revises: deac92ea807e
Create Date: 2024-09-30 14:19:21.630063

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0cf11907d837'
down_revision = 'deac92ea807e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentdataexample', sa.Column('start_page', sa.Integer(), nullable=False))
    op.add_column('documentdataexample', sa.Column('end_page', sa.Integer(), nullable=True))
    op.add_column('documentdataextractor', sa.Column('pydantic_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentdataextractor', 'pydantic_model')
    op.drop_column('documentdataexample', 'end_page')
    op.drop_column('documentdataexample', 'start_page')
    # ### end Alembic commands ###
