"""Process_as is not optional

Revision ID: 17c369c85f64
Revises: a8b878a502f1
Create Date: 2024-12-11 11:19:28.734548

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '17c369c85f64'
down_revision = 'a8b878a502f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentdataextractor', 'process_as',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentdataextractor', 'process_as',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
