"""Add column last_name to User model

Revision ID: 4e92c62b7d90
Revises: 0cf11907d837
Create Date: 2024-09-30 15:12:16.365679

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e92c62b7d90'
down_revision = '0cf11907d837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
