"""Add column to dde to account for json_schema

Revision ID: 5b09eca9fc4d
Revises: 964e3df77cf0
Create Date: 2024-10-11 10:37:47.325026

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "5b09eca9fc4d"
down_revision = "964e3df77cf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documentdataextractor",
        sa.Column(
            "response_template",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documentdataextractor", "response_template")
    # ### end Alembic commands ###
