"""UPdate tables

Revision ID: a3b5b8f12daf
Revises: 0b08d03d3898
Create Date: 2024-03-26 16:16:25.451861

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a3b5b8f12daf'
down_revision = '0b08d03d3898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attribute_name', table_name='attribute')
    op.create_index(op.f('ix_attribute_name'), 'attribute', ['name'], unique=True)
    op.alter_column('eventattribute', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventattribute', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_attribute_name'), table_name='attribute')
    op.create_index('ix_attribute_name', 'attribute', ['name'], unique=False)
    # ### end Alembic commands ###
