apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-frontend-service
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.AppVersion}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - name: tcp-frontend
      port: {{.Values.frontend.service.externalPort}}
      targetPort: {{.Values.frontend.service.internalPort}}
  selector:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/component: frontend
