apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arena-storageclass
{{- if eq .Values.cluster.provider "AKS"}}
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- else if eq .Values.cluster.provider "EKS"}}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- else if eq .Values.cluster.provider "GKE"}}
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- else}}
{{- end}}