# PostgreSQL password
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-postgresql-secret
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/version: {{.Chart.AppVersion}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
